apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "icantbelieveitsnotvaletudo.fullname" . }}
  labels:
{{ include "icantbelieveitsnotvaletudo.labels" . | indent 4 }}
data:
  config.json: |
    {{- .Values.config | mustToPrettyJson | nindent 4 }}
