apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "blocky.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "blocky.name" . }}
    helm.sh/chart: {{ include "blocky.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{- if .Values.config }}
{{ $root := . }}
  config.yml: |
{{ tpl (toYaml .Values.config | indent 4) $root }}
{{- end }}
{{- range $name, $value := .Values.extraLists }}
  {{ $name }}: |-
{{ $value | indent 4}}
{{- end }}
