{{- if and .Values.externalSecret.enabled (eq .Values.externalSecret.type "kubernetes-external-secrets") }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "statping.fullname" . }}
spec:
  {{- with .Values.externalSecret.kubernetesExternalSecrets.spec }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  data:
  {{- with .Values.externalSecret.kubernetesExternalSecrets.data }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}