{{- if and .Values.postgres.enabled (eq .Values.postgres.type "kubedb") }}
apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: postgres-{{ template "statping.fullname" . }}
spec:
  version: {{ .Values.postgres.kubedb.version }}
  storageType: {{ .Values.postgres.kubedb.storageType }}
  {{- with .Values.postgres.kubedb.storage }}
  storage:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}